app/models.py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

from . import db, bcrypt
from itsdangerous import TimedJSONWebSignatureSerializer, BadSignature, SignatureExpired
from . import login_manager
from flask import current_app
from datetime import datetime


class User(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    username = db.Column(db.String(80), unique=True)
    password = db.Column(db.String(120))  # 这个密码可以用来还原的,如果用bcrypt.generate_password_hash来生成密码,则是不能还原的
    sex = db.Column(db.String(10))
    address = db.Column(db.String(255))  # 居住地
    work_address = db.Column(db.String(255))  # 工作地点
    birth = db.Column(db.DateTime, default=datetime.now())  # 出生日期
    year_money = db.Column(db.String(255))  # 年收入
    marital_status = db.Column(db.String(25))  # 婚姻状态 单身，热恋中，已婚
    requirement_opposite = db.Column(db.Text)  # 对异性的要求
    qq = db.Column(db.String(255))
    weixin = db.Column(db.String(255))  # 微信号
    tel = db.Column(db.String(255))  # 电话，唯一字段
    e_mail = db.Column(db.String(255))
    personal_detail = db.Column(db.Text)  # 个人情况说明,谈谈爱好，兴趣，工作内容，家庭状况
    pic_url = db.Column(db.String(255))  # 头像地址

    def __init__(self, username="", password=""):
        self.username = username
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        self.password = bcrypt.generate_password_hash(password)
        # self.password = prpcrypt().encrypt(password)

    def check_password(self, value):
        return bcrypt.check_password_hash(self.password, value)

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return unicode(self.id)

    @staticmethod
    def verify_auth_token(token):
        s = TimedJSONWebSignatureSerializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except SignatureExpired:
            return None
        except BadSignature:
            return None
        user = User.query.get(data['id'])
        return user

    def __str__(self):
        return '<User %r>' % self.username

    __repr__ = __str__
    # s=Student(),repr方法是实例s调用这个主要是作为测试来调用,,str方法时类Student()调用


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/__init__.py
#!/usr/bin/env python
# -*- coding:UTF-8 -*-
from flask import Flask
from flask_bcrypt import Bcrypt
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

from config import config
from loggingHelper import getLogger
from flask_babelex import Babel

bcrypt = Bcrypt()

db = SQLAlchemy()
login_manager = LoginManager()
login_manager.login_view = "auth.login"
login_manager.session_protection = "strong"


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    babel = Babel()
    babel.init_app(app)

    from api.main import main
    app.register_blueprint(main)

    from api.auth import auth
    app.register_blueprint(auth)

    from api.flask_admin import create_admin_page
    create_admin_page(app)

    from api.page_route import meinv, link
    app.register_blueprint(meinv)
    app.register_blueprint(link)

    return app

app/api/__init__.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__)


# from . import views, errors
@main.app_errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404


@main.app_errorhandler(500)
def internal_server_error(e):
    return render_template('errpage/500.html'), 500

app/api/flask_admin/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from flask_admin import Admin, BaseView, expose, AdminIndexView
from flask_admin.contrib.sqla import ModelView
from app.models import User
from app import db
from wtforms import PasswordField
from flask_login import current_user

# admin_page = Admin(name=u'基础配置', index_view=AdminIndexView(name=u"导航栏", url='/admin'), template_mode='bootstrap3')
admin_page = Admin(name=u'基础配置', template_mode='bootstrap3')


class MyView(ModelView):
    def is_accessible(self):
        if current_user.is_authenticated and current_user.username == "root":
            return True
        return False


# class DBNSDeviceModelView(ModelView):
#     # column_exclude_list = ['name', 'displayName', 'configTime', 'persistProfileName', 'zone', ]
#     column_select_related_list = DBNSDevice.zone_id
#     page_size = 20

class UserView(MyView):
    # form_excluded_columns = ('password')
    form_extra_fields = {
        'setPassword': PasswordField('newpassword')
    }
    # set the form fields to use
    form_columns = (
        'username',
        'password',
        'setPassword'
    )

    def on_model_change(self, form, User, is_created):  # password加密时bcrypt的写法
        # def on_model_change(self, form, User):
        if form.setPassword.data is not None:
            User.set_password(form.setPassword.data)
            # del form.password

    def on_form_prefill(self, form, id):
        # form.password.data = ''
        pass

    column_filters = ('username', 'password')
# class MyView(BaseView):
#     @expose('/')
#     def index(self):
#         return self.render('deviceEdit.html')


def create_admin_page(app):
    admin_page.init_app(app)
    admin_page.add_view(UserView(User, db.session, name=u"用户"))
    # admin_page.add_view(MyView(name=u'设备信息'))
    # admin_page.add_view(MyView(name='Hello 3',endpoint='test3', category=u'设备信息'))

app/api/main/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, error

app/api/main/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from flask import render_template
from . import main
from flask_login import login_required


# from decorater import login_required


@main.route('/', methods=['GET', 'POST'])
# @login_required
def index():
    return render_template('index.html')
    # 需要写一个装饰器，判断是否登录，如果登录了，则跳到index,并生成对应的menu


@main.route('/teacher', methods=['GET', 'POST'])
def teacher_index():
    return render_template('/teacher/index.html')
    # 需要写一个装饰器，判断是否登录，如果登录了，则跳到index,并生成对应的menu

app/api/page_route/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from .link import link
from .meizi import meinv

app/api/page_route/link/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template

link = Blueprint('link', __name__)


@link.route('/link')
def link_index():
    return render_template("link/link.html", title=u"这个是我们的link")

app/api/page_route/meizi/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template

meinv = Blueprint('meinv', __name__, url_prefix="/meizi")


@meinv.route('/pic')
def meinv_pic():
    return render_template("meizi/meizi.html", title=u'精彩的妹子图片')

app/templates/base.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    {% block styles %}
        <link href="{{ url_for('static',filename='css/bootstrap.min.css') }}" rel="stylesheet" media="screen"/>
        <link href="{{ url_for('static',filename='css/personal/basic.css') }}" rel="stylesheet"/>
    {% endblock styles %}
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
{% include "parents_menu.html" %}
{% block body_content %}{% endblock body_content %}
{% block body_js %}
    <script src="{{ url_for('static',filename='js/jquery-3.2.1.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/bootstrap.min.js') }}"></script>
{% endblock body_js %}
<hr class="divider">
<div class="foot_div">
    <footer>
        <p class="pull-right footer-top"><a href="#top"> 回到顶部</a></p>
        <p class="footer-p"> Design by WangJing @2017</p>
    </footer>
</div>
{#弹出框#}
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">本站信息</h4>
            </div>
            <div class="modal-body">
                <h2>本站信息</h2>
                <p>开发框架：Flask + Bootstrap + Angularjs</p>
                <p>中间件：Nginx +uswgi</p>
                <p>开放者：WangJing</p>
                <p>业务微信：timorkinger</p>
            </div>
            <div class="modal-footer">
                <a href="mailto:289363142@qq.com">给我发邮件</a>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
</body>
</html>

app/templates/errpage/401.html
You  are unauthorized to access the URL requested

app/templates/index.html
{% extends "base.html" %}
{% block title %}My Flask  WebSite{% endblock title %}
{% block styles %}
    {{ super() }}
    <link href="{{ url_for('static',filename='css/personal/carousel.css') }}" rel="stylesheet"/>
{% endblock %}
{% block body_content %}
    {#    轮播组件开始#}
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <a href="http://www.baidu.com" target="_blank"><img
                        src="{{ url_for('static',filename='pic/safari.jpg') }}" alt="safari"></a>
            </div>
            <div class="item">
                <a href="http://www.baidu.com" target="_blank"><img
                        src="{{ url_for('static',filename='pic/opera.jpg') }}" alt="opera"></a>
            </div>
            <div class="item">
                <a href="http://www.baidu.com" target="_blank"><img
                        src="{{ url_for('static',filename='pic/firefox.jpg') }}" alt="firefox"></a>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="FALSE"></span>
            <span class="sr-only">上一页</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">下一页</span>
        </a>
        {#    轮播组件结束#}
    </div>
    {#    三栏布局#}
    <div class="container" id="sumary-container">
        <div class="row">
            <div class="col-md-4">
                <img src="{{ url_for('static',filename='pic/opera.jpg') }}" alt="safari">
                <h2>一个飞快的浏览器</h2>
                <a class="btn btn-lg btn-primary" href="#" role="button">点击我下载</a>
            </div>
            <div class="col-md-4">
                <img src="{{ url_for('static',filename='pic/opera.jpg') }}" alt="safari">
                <h2>一个飞快的浏览器</h2>
                <a class="btn btn-lg btn-primary" href="#" role="button">点击我下载</a>
            </div>
            <div class="col-md-4">
                <img src="{{ url_for('static',filename='pic/opera.jpg') }}" alt="safari">
                <h2>一个飞快的浏览器</h2>
                <a class="btn btn-lg btn-primary" href="#" role="button">点击我下载</a>
            </div>
        </div>
        <hr class="divider">
        <div>

            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab"
                                                          data-toggle="tab">FireFox</a>
                </li>
                <li role="presentation"><a href="#profile" aria-controls="profile" role="tab"
                                           data-toggle="tab">Opera</a>
                </li>
                <li role="presentation"><a href="#messages" aria-controls="messages" role="tab"
                                           data-toggle="tab">chorme</a></li>
                <li class="下拉">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Others <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li role="presentation">
                            <a href="#first" aria-controls="frist" role="tab"
                               data-toggle="tab">first</a>
                        </li>
                        <li role="presentation">
                            <a href="#second" aria-controls="second" role="tab"
                               data-toggle="tab">second</a>
                        </li>
                        <li role="presentation">
                            <a href="#third" aria-controls="third" role="tab"
                               data-toggle="tab">third</a>
                        </li>
                    </ul>
                </li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="home">
                    <div class="row feature">
                        <div class="col-md-7">
                            <h2 class="feature-heading">opera<span class="text-muted">用户首选</span></h2>
                            <p class="lead">opera浏览器只为给你最好的体验,opera浏览器只为给你最好的体验</p>
                        </div>
                        <div class="col-md-5">
                            <img class="feature-image img-responsive"
                                 src="{{ url_for('static',filename='pic/opera.jpg') }}" alt="opera"></div>
                    </div>
                </div>
                <div role="tabpanel" class="tab-pane" id="profile">
                    <div class="row feature">
                        <div class="col-md-5">
                            <h2 class="feature-heading">opera<span class="text-muted">用户首选</span></h2>
                            <p class="lead">opera浏览器只为给你最好的体验,opera浏览器只为给你最好的体验</p>
                        </div>
                        <div class="col-md-7">
                            <img class="feature-image img-responsive"
                                 src="{{ url_for('static',filename='pic/opera.jpg') }}" alt="opera"></div>
                    </div>
                </div>
                <div role="tabpanel" class="tab-pane" id="messages">
                    <div class="row feature">
                        <div class="col-md-7">
                            <h2 class="feature-heading">opera<span class="text-muted">用户首选</span></h2>
                            <p class="lead">opera浏览器只为给你最好的体验,opera浏览器只为给你最好的体验</p>
                        </div>
                        <div class="col-md-5">
                            <img class="feature-image img-responsive"
                                 src="{{ url_for('static',filename='pic/opera.jpg') }}" alt="opera"></div>
                    </div>
                </div>
                {#                下拉菜单#}

                <div role="tabpanel" class="tab-pane" id="first" aria-labelledby="dropdown1-tab">
                    <div class="row feature">
                        <h2 class="feature-heading">opera<span class="text-muted"> Fist</span></h2>
                    </div>
                </div>
                <div role="tabpanel" class="tab-pane" id="second" aria-labelledby="dropdown1-tab">
                    <div class="row feature"><h2 class="feature-heading">opera<span class="text-muted"> second</span>
                    </h2>
                    </div>
                </div>
                <div role="tabpanel" class="tab-pane" id="third" aria-labelledby="dropdown1-tab">
                    <div class="row feature">
                        <h2 class="feature-heading">opera<span class="text-muted"> third</span></h2>
                    </div>
                </div>
            </div>

        </div>
    </div>
    {#标签页#}


    <div class="text-center">
        <div><h3>welcome to my first Web,尊敬的{{ current_user.username }}!</h3></div>
        <!-- Button trigger modal -->
    </div>

{% endblock body_content %}
{% block body_js %}
    {{ super() }}
{% endblock body_js %}

app/templates/menu.html
{#<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">#}
<nav class="navbar navbar-default navbar-fixed-top">
    {#    <div class="container-fluid">#}
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            {#            <a class="navbar-brand" href="{{ url_for("main.index") }}">测试网</a>#}
            <a class="navbar-brand" href="/">快乐幼儿园</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for("link.link_index") }}">首页</a></li>
                <li><a href="{{ url_for("meinv.meinv_pic") }}">每日三好学生展示<span class="sr-only">(current)</span></a></li>
                <li><a href="{{ url_for("link.link_index") }}">教师风采</a></li>
                <li><a href="{{ url_for("link.link_index") }}">学校简介</a></li>
                <li><a href="{{ url_for("link.link_index") }}">成功案例</a></li>
                <li><a href="{{ url_for("link.link_index") }}">结婚礼品</a></li>
                <li><a href="{{ url_for("link.link_index") }}">化妆摄影</a></li>
                <li><a href="{{ url_for("link.link_index") }}">商家注册</a></li>
{#                <li class="dropdown">#}
{#                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"#}
{#                       aria-expanded="false">更多信息 <span class="caret"></span></a>#}
{#                    <ul class="dropdown-menu">#}
{#                        <li><a href="#">Action</a></li>#}
{#                        <li><a href="#">Another action</a></li>#}
{#                        <li><a href="#">Something else here</a></li>#}
{#                        <li role="separator" class="divider"></li>#}
{#                        <li><a href="#">Separated link</a></li>#}
{#                        <li role="separator" class="divider"></li>#}
{#                        <li><a href="#">One more separated link</a></li>#}
{#                    </ul>#}
{#                </li>#}
            </ul>
{#            <form class="navbar-form navbar-left">#}
{#                <div class="form-group">#}
{#                    <input type="text" class="form-control" placeholder="Search">#}
{#                </div>#}
{#                <button type="submit" class="btn btn-default">Submit</button>#}
{#            </form>#}
            <ul class="nav navbar-nav navbar-right">

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">尊敬的{{ current_user.username }}! <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="/admin">系统管理</a></li>
                        <li><a href="/admin">私信</a></li>
                        <li><a href="{{ url_for("auth.logout") }}">退出</a></li>
                    </ul>
                </li>
                <li class="active"><a href="#" data-toggle="modal" data-target="#myModal">关于本站</a>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

{#{% for first_level_menu in first_level%}#}
{#<ul>{{first_level_menu.sectionName}}#}
{#    {% for second_levell_menu in second_level%}#}
{#    {%if second_levell_menu.parent_id==first_level_menu.id %}#}
{#    <ul><a href="{{second_levell_menu.sectionURL}}">{{second_levell_menu.sectionName}}</a>#}
{#        {% for thrid_level_menu in thrid_level%}#}
{#        {%if thrid_level_menu.parent_id==second_levell_menu.id %}#}
{#        <ul><a href="{{thrid_level_menu.sectionURL}}">{{thrid_level_menu.sectionName}}</a></ul>#}
{#        {%endif%}#}
{#        {%endfor%}#}
{#    </ul>#}
{#    {%endif%}#}
{#    {%endfor%}#}
{#</ul>#}
{#{%endfor%}#}

app/templates/parents_menu.html
{#<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">#}
<nav class="navbar navbar-default navbar-fixed-top">
    {#    <div class="container-fluid">#}
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            {#            <a class="navbar-brand" href="{{ url_for("main.index") }}">测试网</a>#}
            <a class="navbar-brand" href="/">快乐幼儿园</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for("link.link_index") }}">首页</a></li>
                <li><a href="{{ url_for("meinv.meinv_pic") }}">每日三好学生展示<span class="sr-only">(current)</span></a></li>
                <li><a href="{{ url_for("link.link_index") }}">教师风采</a></li>
                <li><a href="{{ url_for("link.link_index") }}">学校简介</a></li>
                <li><a href="{{ url_for("link.link_index") }}">成功案例</a></li>
                <li><a href="{{ url_for("link.link_index") }}">结婚礼品</a></li>
                <li><a href="{{ url_for("link.link_index") }}">化妆摄影</a></li>
                <li><a href="{{ url_for("link.link_index") }}">商家注册</a></li>
{#                <li class="dropdown">#}
{#                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"#}
{#                       aria-expanded="false">更多信息 <span class="caret"></span></a>#}
{#                    <ul class="dropdown-menu">#}
{#                        <li><a href="#">Action</a></li>#}
{#                        <li><a href="#">Another action</a></li>#}
{#                        <li><a href="#">Something else here</a></li>#}
{#                        <li role="separator" class="divider"></li>#}
{#                        <li><a href="#">Separated link</a></li>#}
{#                        <li role="separator" class="divider"></li>#}
{#                        <li><a href="#">One more separated link</a></li>#}
{#                    </ul>#}
{#                </li>#}
            </ul>
{#            <form class="navbar-form navbar-left">#}
{#                <div class="form-group">#}
{#                    <input type="text" class="form-control" placeholder="Search">#}
{#                </div>#}
{#                <button type="submit" class="btn btn-default">Submit</button>#}
{#            </form>#}
            <ul class="nav navbar-nav navbar-right">

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">尊敬的{{ current_user.username }}! <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="/admin">系统管理</a></li>
                        <li><a href="/admin">私信</a></li>
                        <li><a href="{{ url_for("auth.logout") }}">退出</a></li>
                    </ul>
                </li>
                <li class="active"><a href="#" data-toggle="modal" data-target="#myModal">关于本站</a>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

{#{% for first_level_menu in first_level%}#}
{#<ul>{{first_level_menu.sectionName}}#}
{#    {% for second_levell_menu in second_level%}#}
{#    {%if second_levell_menu.parent_id==first_level_menu.id %}#}
{#    <ul><a href="{{second_levell_menu.sectionURL}}">{{second_levell_menu.sectionName}}</a>#}
{#        {% for thrid_level_menu in thrid_level%}#}
{#        {%if thrid_level_menu.parent_id==second_levell_menu.id %}#}
{#        <ul><a href="{{thrid_level_menu.sectionURL}}">{{thrid_level_menu.sectionName}}</a></ul>#}
{#        {%endif%}#}
{#        {%endfor%}#}
{#    </ul>#}
{#    {%endif%}#}
{#    {%endfor%}#}
{#</ul>#}
{#{%endfor%}#}

app/templates/teacher/menu.html
{#<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">#}
<nav class="navbar navbar-default navbar-fixed-top">
    {#    <div class="container-fluid">#}
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">快乐幼儿园</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for("main.teacher_index") }}">学校管理页面</a></li>
                <li><a href="{{ url_for("main.teacher_index") }}">学生资料<span class="sr-only">(current)</span></a></li>
                <li><a href="{{ url_for("main.teacher_index") }}">学生动态<span class="sr-only">(current)</span></a></li>
                <li><a href="{{ url_for("main.teacher_index") }}">留言回复<span class="sr-only">(current)</span></a></li>
                <li><a href="{{ url_for("main.teacher_index") }}">教师资料<span class="sr-only">(current)</span></a></li>
                <li><a href="{{ url_for("main.teacher_index") }}">学校资料<span class="sr-only">(current)</span></a></li>
                <li><a href="{{ url_for("main.teacher_index") }}">课程设置<span class="sr-only">(current)</span></a></li>
                <li><a href="{{ url_for("main.teacher_index") }}">学校公告<span class="sr-only">(current)</span></a></li>
                <li><a href="{{ url_for("main.teacher_index") }}">工作总结<span class="sr-only">(current)</span></a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">尊敬的{{ current_user.username }}! <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="/admin">系统管理</a></li>
                        <li><a href="/admin">私信</a></li>
                        <li><a href="{{ url_for("auth.logout") }}">退出</a></li>
                    </ul>
                </li>
                <li class="active"><a href="#" data-toggle="modal" data-target="#myModal">关于本站</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/templates/upload.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css"
          rel="stylesheet">
  </head>
  <body>
    <div class="container">
      <div class="header">
        <h3 class="text-muted">How To Upload a File</h3>
      </div>
      <hr/>
      <div>
      
      <form action="upload" method="post" enctype="multipart/form-data">
        <input type="file" name="file"><br /><br />
        <input type="submit" value="Upload">
      </form>
      </div>
    </div>
  </body>
</html>
 